version: '3.8'

services:
    purchaser_nginx:
        container_name: purchaser_nginx
        image: nginx:stable-alpine
        ports:
            - '8088:80'
        volumes:
            - ../backend:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - purchaser_php
        networks:
            - purchaser_network
    purchaser_php:
        container_name: purchaser_php
        depends_on:
            - purchaser_database
        build:
            context: ./php
        ports:
            - '9000:9000'
        volumes:
            - ../backend/:/var/www/html/
        networks:
            - purchaser_network

    purchaser_database:
        container_name: purchaser_database
        image: mysql:8.0
        restart: on-failure
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: purchaser
            MYSQL_USER: admin
            MYSQL_PASSWORD: password
        ports:
            - '3367:3306'
        volumes:
            - /opt/purchaser_database:/var/lib/mysql
        networks:
            - purchaser_network

    purchaser_phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 9999:80
        depends_on:
            - purchaser_database
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=purchaser_database
        container_name: purchaser_phpmyadmin
        networks:
            - purchaser_network
    purchaser_frontend:
        image: node:18-alpine
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=dev
        volumes:
            - ../frontend/:/home/node/app
        ports:
            - 3333:3000
        command: sh -c "npm install && npm run start"
        restart: on-failure
        container_name: purchaser_frontend
        networks:
            - purchaser_network

networks:
    purchaser_network:
        external: true
        driver: bridge

