version: '3.8'

services:
    purchaser_php:
        container_name: purchaser_php
        depends_on:
            - purchaser_database
        build:
            context: ./php
        ports:
            - '9000:9000'
            - '8088:8000'
        volumes:
            - ../backend/:/var/www/html/
        command: bash -c "php artisan serve --host=0.0.0.0 --port=8000 --no-ansi"
        networks:
            - purchaser_network

    purchaser_database:
        container_name: purchaser_database
        image: mysql:8.0
        restart: on-failure
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: purchaser
            MYSQL_USER: admin
            MYSQL_PASSWORD: password
        ports:
            - '3367:3306'
        volumes:
            - /opt/purchaser_database:/var/lib/mysql
        networks:
            - purchaser_network

    purchaser_phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 9999:80
        depends_on:
            - purchaser_database
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=purchaser_database
        container_name: purchaser_phpmyadmin
        networks:
            - purchaser_network

networks:
    purchaser_network:
        external: true
        driver: bridge

